name: myapp
description: Screen by Nikhil Smart E invites


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/page-1/images/vector.png
    - assets/page-1/images/vector-6W4.png
    - assets/page-1/images/vector-3Jg.png
    - assets/page-1/images/group.png
    - assets/page-1/images/fi-ss-angle-left.png
    - assets/page-1/images/image-29.png
    - assets/page-1/images/vector-Rag.png
    - assets/page-1/images/verti-truck-1-3.png
    - assets/page-1/images/vector-qXW.png
    - assets/page-1/images/fi-ss-share.png
    - assets/page-1/images/image-28.png
    - assets/page-1/images/fi-ss-share-usn.png
    - assets/page-1/images/rectangle.png
    - assets/page-1/images/destiverti-1-2.png
    - assets/page-1/images/fi-ss-eye.png
    - assets/page-1/images/image-33.png
    - assets/page-1/images/vector-Bwn.png
    - assets/page-1/images/vector-Gbr.png
    - assets/page-1/images/fi-ss-eye-ZC4.png
    - assets/page-1/images/group-E1v.png
    - assets/page-1/images/fi-ss-share-McL.png
    - assets/page-1/images/vector-MV2.png
    - assets/page-1/images/vector-Vd2.png
    - assets/page-1/images/vector-rLQ.png
    - assets/page-1/images/vector-qKN.png
    - assets/page-1/images/vector-m6Y.png
    - assets/page-1/images/vector-WEU.png
    - assets/page-1/images/group-pbr.png
    - assets/page-1/images/fi-ss-eye-ZMi.png
    - assets/page-1/images/vector-WXr.png
    - assets/page-1/images/vector-tYQ.png
    - assets/page-1/images/vector-C7A.png
    - assets/page-1/images/group-sFE.png
    - assets/page-1/images/vector-67z.png
    - assets/page-1/images/group-Qqv.png
    - assets/page-1/images/vector-VPW.png
    - assets/page-1/images/fi-ss-share-Noz.png
    - assets/page-1/images/vector-eWc.png
    - assets/page-1/images/group-187.png
    - assets/page-1/images/vector-EUg.png
    - assets/page-1/images/image-34.png
    - assets/page-1/images/ellipse-53-bg.png
    - assets/page-1/images/vector-W9n.png
    - assets/page-1/images/background.png
    - assets/page-1/images/fi-ss-eye-bH2.png
    - assets/page-1/images/verti-truck-1-2.png
    - assets/page-1/images/group-hep.png
    - assets/page-1/images/group-Loa.png
    - assets/page-1/images/vector-Lrk.png
    - assets/page-1/images/group-JYg.png
    - assets/page-1/images/group-186.png
    - assets/page-1/images/group-187-Yz4.png
    - assets/page-1/images/fi-ss-share-SJk.png
    - assets/page-1/images/image-35.png
    - assets/page-1/images/verti-truck-1-3-Hg4.png
    - assets/page-1/images/vector-PUC.png
    - assets/page-1/images/logo1.png
    - assets/page-1/images/vector-ZBN.png
    - assets/page-1/images/group-WMW.png
    - assets/page-1/images/fi-ss-eye-1wn.png
    - assets/page-1/images/fi-ss-share-w4k.png
    - assets/page-1/images/group-AhW.png
    - assets/page-1/images/fi-ss-share-MjN.png
    - assets/page-1/images/verti-truck-1-3-nEt.png
    - assets/page-1/images/group-Z8U.png
    - assets/page-1/images/verticle-2-3.png
    - assets/page-1/images/vector-6wS.png
    - assets/page-1/images/vector-TX6.png
    - assets/page-1/images/vector-5PN.png
    - assets/page-1/images/vector-iuW.png
    - assets/page-1/images/verti-truck-1-2-7Vi.png
    - assets/page-1/images/vector-3Xn.png
    - assets/page-1/images/fi-ss-arrow-small-up.png
    - assets/page-1/images/vector-YzL.png
    - assets/page-1/images/image-32.png
    - assets/page-1/images/group-WLp.png
    - assets/page-1/images/verti-truck-1-2-ose.png
    - assets/page-1/images/fi-ss-eye-vhN.png
    - assets/page-1/images/vector-GmE.png
    - assets/page-1/images/fi-ss-share-fk4.png
    - assets/page-1/images/group-yPN.png
    - assets/page-1/images/vector-MKN.png
    - assets/page-1/images/group-aFJ.png
    - assets/page-1/images/vector-4.png
    - assets/page-1/images/verti-truck-1-4.png
    - assets/page-1/images/fi-ss-eye-uHz.png
    - assets/page-1/images/image-31.png
    - assets/page-1/images/group-FbN.png
    - assets/page-1/images/group-JWC.png
    - assets/page-1/images/image-30.png
    - assets/page-1/images/vector-dkk.png
    - assets/page-1/images/fi-ss-eye-gMe.png
    - assets/page-1/images/fi-ss-eye-Z44.png
    - assets/page-1/images/vector-5.png
    - assets/page-1/images/fi-ss-share-ezU.png
    - assets/page-1/images/vector-txg.png
    - assets/page-1/images/subtract.png
    - assets/page-1/images/fi-ss-eye-Xtk.png
    - assets/page-1/images/vector-3.png
    - assets/page-1/images/fi-ss-share-YC8.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
